# ForecastEx - forcus on NYC Mayor group forecast

## Web REST API

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import requests, json, os
from pprint import pprint

## Get live markets

In [3]:
from get_live_markets import get_live_markets
markets = get_live_markets()

In [4]:
from add_category_to_markets import add_category_to_markets
df_markets = add_category_to_markets(markets)

In [5]:
df_markets = df_markets[['category', 'name', 'symbol', 'conid']].sort_values(by=['category', 'name'])

In [6]:
conid_to_market = {market['conid']: market for market in markets}

In [10]:
df_markets[df_markets.symbol == 'MNYCG']

   category                                      name symbol      conid
0  Election  General Election for New York City Mayor  MNYCG  796056051

In [12]:
market = markets[0]
market

{'symbol': 'MNYCG',
 'conid': 796056051,
 'name': 'General Election for New York City Mayor'}

## Get forecastex markets excluding financials

In [13]:
from fetch_all_contracts import fetch_all_contracts
from tqdm.auto import tqdm

In [14]:
for market in tqdm(markets):
    if 'contracts' not in market:
        market['contracts'] = fetch_all_contracts(market['conid'])
        print(market['conid'], len(market['contracts']))
    break

  0%|          | 0/211 [00:00<?, ?it/s]

796056051 10

In [20]:
forecastex = [market] #  for market in markets if len(market['contracts']) > 0]

In [21]:
len(markets), len(forecastex)

(211, 1)

## Get current probability for each market contract

In [22]:
from get_candidate_probability import get_candidate_probability

In [23]:
from tqdm.auto import tqdm

In [24]:
for market in tqdm(forecastex):
    for contract in market['contracts']:
        conid = contract['conid']
        if 'probability' not in contract:
            try:
                contract['probability'] = get_candidate_probability(conid)
            except:
                contract['probability'] = None
                print('error', contract['shortDescription'])
        try:
            print(conid, contract['shortDescription'], contract['probability']['probability_pct'])
        except:
            pass

  0%|          | 0/1 [00:00<?, ?it/s]

796056496 MNYCG Nov04'25 Sliwa YES @FORECASTX 5.0
796056501 MNYCG Nov04'25 Sliwa NO @FORECASTX 96.0
796056506 MNYCG Nov04'25 Cuomo YES @FORECASTX 16.0
796056511 MNYCG Nov04'25 Cuomo NO @FORECASTX 85.0
796056520 MNYCG Nov04'25 Mamdani YES @FORECASTX 68.0
796056525 MNYCG Nov04'25 Mamdani NO @FORECASTX 33.0
796056531 MNYCG Nov04'25 Adams YES @FORECASTX 8.0
796056534 MNYCG Nov04'25 Adams NO @FORECASTX 93.0

In [25]:
f2 = [x.copy() for x in forecastex]

In [26]:
for market in f2:
    market['contracts'] = [x for x in market['contracts'] if x['probability']]

In [27]:
f2 = [market for market in f2 if market['contracts']]

## Open Interest (must run chrome in debug mode)

https://www.perplexity.ai/search/how-do-i-do-this-request-in-py-LKWOZo0lRNegn9r7ALA1dw

google-chrome   --remote-debugging-port=9222   --user-data-dir="$HOME/.chrome-debug-test"   https://forecasttrader.interactivebrokers.com/eventtrader/ &
curl http://localhost:9222/json

In [30]:
from OI_to_integer import OI_to_integer

In [31]:
from run_get_OI import run_get_OI

In [32]:
for market in tqdm(f2):
    for contract in tqdm(market['contracts']):
        if 'OI' not in contract:
            conid = contract['conid']
            OI = await run_get_OI([conid])
            OI = list(OI.values())[0]
            contract['OI'] = OI_to_integer(OI)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

WebSocket opened, sending requests for 1 conids...
Received OI for conid 796056496: 68.3K
Received all expected OI results, closing WebSocket.
✅ Received OI results for all conids.
WebSocket closed with code=None, message=None
WebSocket opened, sending requests for 1 conids...
Received OI for conid 796056501: 68.3K
Received all expected OI results, closing WebSocket.
✅ Received OI results for all conids.
WebSocket opened, sending requests for 1 conids...
Received OI for conid 796056506: 27.8K
Received all expected OI results, closing WebSocket.
✅ Received OI results for all conids.
WebSocket closed with code=None, message=None
WebSocket closed with code=None, message=None
WebSocket opened, sending requests for 1 conids...
Received OI for conid 796056511: 27.8K
Received all expected OI results, closing WebSocket.
✅ Received OI results for all conids.
WebSocket closed with code=None, message=None
WebSocket opened, sending requests for 1 conids...
Received OI for conid 796056520: 1.20M
Received all expected OI results, closing WebSocket.
✅ Received OI results for all conids.
WebSocket closed with code=None, message=None
WebSocket opened, sending requests for 1 conids...
Received OI for conid 796056525: 1.20M
Received all expected OI results, closing WebSocket.
✅ Received OI results for all conids.
WebSocket closed with code=None, message=None
WebSocket opened, sending requests for 1 conids...
Received OI for conid 796056531: 202K
Received all expected OI results, closing WebSocket.
✅ Received OI results for all conids.
WebSocket closed with code=None, message=None
WebSocket opened, sending requests for 1 conids...
Received OI for conid 796056534: 202K
Received all expected OI results, closing WebSocket.
✅ Received OI results for all conids.
WebSocket closed with code=None, message=None

## Collect and filter

In [34]:
rows = []
for market in f2:
    for ctx in market['contracts']:
        contract = ctx.copy()
        probability = contract['probability']
        contract['probability_pct'] = probability['probability_pct']
        contract['weekly_volume'] = sum(probability['volume'])
        contract['yesNo'] = 'YES' if contract['putOrCall'] == 'C' else 'NO'
        for x in ['putOrCall','popularityRank', 'expiration', 'lastTradeMillis', 'lastTradeTime','eventFixedPayout', 'commodityCode', 'strike', 'market',
                    'categories', 'expectedResolutionTime', 'expectedPayoutTime', 'timespecifierParam', 'sourceAgency', 'marketRulesLink', 
                    'exchange', 'priceIncrement', 'currency', 'timezone', 'eventAuthorityURL', 'probability', 'tradingHours']:
            del contract[x]
        rows.append(contract)

In [41]:
from add_category_to_markets import add_category_to_markets
df = add_category_to_markets(rows, 'longDescription')

In [37]:
df

,name,longDescription,lastTradeDate,underlyingName,conid,underlyingConid,underlyingSymbol,shortDescription,strikeLabel,OI,probability_pct,weekly_volume,yesNo,category
0,MNYCG Nov04'25 Sliwa,Will Curtis Sliwa win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056496,796056051,MNYCG,MNYCG Nov04'25 Sliwa YES @FORECASTX,Sliwa,68300.0,5.0,4130.0,YES,Election
1,MNYCG Nov04'25 Sliwa,Will Curtis Sliwa win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056501,796056051,MNYCG,MNYCG Nov04'25 Sliwa NO @FORECASTX,Sliwa,68300.0,96.0,4130.0,NO,Election
2,MNYCG Nov04'25 Cuomo,Will Andrew Cuomo win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056506,796056051,MNYCG,MNYCG Nov04'25 Cuomo YES @FORECASTX,Cuomo,27800.0,16.0,2775.0,YES,Election
3,MNYCG Nov04'25 Cuomo,Will Andrew Cuomo win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056511,796056051,MNYCG,MNYCG Nov04'25 Cuomo NO @FORECASTX,Cuomo,27800.0,85.0,2775.0,NO,Election
4,MNYCG Nov04'25 Mamdani,Will Zohran Mamdani win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056520,796056051,MNYCG,MNYCG Nov04'25 Mamdani YES @FORECASTX,Mamdani,1200000.0,68.0,40527.0,YES,Election
5,MNYCG Nov04'25 Mamdani,Will Zohran Mamdani win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056525,796056051,MNYCG,MNYCG Nov04'25 Mamdani NO @FORECASTX,Mamdani,1200000.0,33.0,40527.0,NO,Election
6,MNYCG Nov04'25 Adams,Will Eric Adams win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056531,796056051,MNYCG,MNYCG Nov04'25 Adams YES @FORECASTX,Adams,202000.0,8.0,10940.0,YES,Election
7,MNYCG Nov04'25 Adams,Will Eric Adams win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056534,796056051,MNYCG,MNYCG Nov04'25 Adams NO @FORECASTX,Adams,202000.0,93.0,10940.0,NO,Election

In [40]:
from datetime import datetime

In [43]:
market.keys()

dict_keys(['symbol', 'conid', 'name', 'contracts'])

In [99]:
df_yes = df[df.yesNo == 'YES']
df_yes

,name,longDescription,lastTradeDate,underlyingName,conid,underlyingConid,underlyingSymbol,shortDescription,strikeLabel,OI,probability_pct,weekly_volume,yesNo,category
0,MNYCG Nov04'25 Sliwa,Will Curtis Sliwa win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056496,796056051,MNYCG,MNYCG Nov04'25 Sliwa YES @FORECASTX,Sliwa,68300.0,5.0,4130.0,YES,Election
2,MNYCG Nov04'25 Cuomo,Will Andrew Cuomo win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056506,796056051,MNYCG,MNYCG Nov04'25 Cuomo YES @FORECASTX,Cuomo,27800.0,16.0,2775.0,YES,Election
4,MNYCG Nov04'25 Mamdani,Will Zohran Mamdani win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056520,796056051,MNYCG,MNYCG Nov04'25 Mamdani YES @FORECASTX,Mamdani,1200000.0,68.0,40527.0,YES,Election
6,MNYCG Nov04'25 Adams,Will Eric Adams win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056531,796056051,MNYCG,MNYCG Nov04'25 Adams YES @FORECASTX,Adams,202000.0,8.0,10940.0,YES,Election

In [105]:
bins = df_yes.apply(lambda row: f'{row.longDescription}', axis=1).values.tolist()

In [106]:
bins

['Will Curtis Sliwa win the New York City general election for mayor in 2025?',
 'Will Andrew Cuomo win the New York City general election for mayor in 2025?',
 'Will Zohran Mamdani win the New York City general election for mayor in 2025?',
 'Will Eric Adams win the New York City general election for mayor in 2025?']

In [107]:
bins = [{'props': {'title': bin, 'ai_title': '', 'order': 0, 'color': ''}, 'isActive': True, 'endDay': 0}
        for bin in bins]

In [108]:
ifp = {'id': market['conid'],
        'type': 'bins',
        'state': 'active',
        'dates': {'startDay': str(datetime.now())[0:10].replace('-',''),'endDay': contract['lastTradeDate']},
        'props': {'title': market['name'], 'shortTitle': '', 'details': ''},
        'kind': 'discrete',
        'bins': bins}

In [109]:
ifp

{'id': 796056051,
 'type': 'bins',
 'state': 'active',
 'dates': {'startDay': '20250729', 'endDay': '20251129'},
 'props': {'title': 'General Election for New York City Mayor',
  'shortTitle': '',
  'details': ''},
 'kind': 'discrete',
 'bins': [{'props': {'title': 'Will Curtis Sliwa win the New York City general election for mayor in 2025?',
    'ai_title': '',
    'order': 0,
    'color': ''},
   'isActive': True,
   'endDay': 0},
  {'props': {'title': 'Will Andrew Cuomo win the New York City general election for mayor in 2025?',
    'ai_title': '',
    'order': 0,
    'color': ''},
   'isActive': True,
   'endDay': 0},
  {'props': {'title': 'Will Zohran Mamdani win the New York City general election for mayor in 2025?',
    'ai_title': '',
    'order': 0,
    'color': ''},
   'isActive': True,
   'endDay': 0},
  {'props': {'title': 'Will Eric Adams win the New York City general election for mayor in 2025?',
    'ai_title': '',
    'order': 0,
    'color': ''},
   'isActive': True,
   'endDay': 0}]}

In [110]:
ifps = [ifp]

In [111]:
from save_ifps_to_disk import save_ifps_to_disk
id_to_ifp = save_ifps_to_disk(ifps)

In [59]:
from gather_news_for_ifps import gather_news_for_ifps
news = gather_news_for_ifps(ifps)

saved glimt/news/796056051.txt

In [60]:
from detailed_proposition import detailed_proposition
from wiki_semantic_search import wiki_semantic_search
from split_news_into_text_and_urls import split_news_into_text_and_urls
from create_source_summaries import create_source_summaries
from rephrase_binary_outcomes import rephrase_binary_outcomes
from format_research import format_research
from glimt_forecast_prompt import glimt_forecast_prompt
from humor_me import humor_me
from get_forecast_components import *
from median_forecast import median_forecast
from median_rationale import median_rationale
from datetime import datetime

loading massive wiki index 2025-07-29 12:28:22.153708
loading wiki article titles 2025-07-29 12:29:29.927931
loading sentence transformer model 2025-07-29 12:29:33.290405
done 2025-07-29 12:29:36.057917

In [61]:
for ifp in ifps:
    break

In [ ]:
    print('begin FORECASTING', ifp['id'], ifp['props']['title'], datetime.now())
    title_plus_criteria = detailed_proposition(ifp)
    wiki_articles = wiki_semantic_search(title_plus_criteria)
    ifp_news_sources, ifp_news_text = split_news_into_text_and_urls(ifp, news)

In [ ]:
    source_summaries, sources = create_source_summaries(ifp['id'], title_plus_criteria, wiki_articles, ifp_news_sources, ifp_news_text)
    rephrase_binary_outcomes(ifp)
    research = format_research(source_summaries)

In [118]:
import json
from saved_prompt import saved_prompt
from get_periods_of_whenwill_question import get_periods_of_whenwill_question
from filter_periods_to_today import filter_periods_to_today
from get_event import get_event
from is_election import is_election

def glimt_forecast_prompt(ifp, research):
    (fn, savep) = saved_prompt(ifp)
    if savep: return savep
    ## Prompt with rationale fields split into for and against
    details = ifp['props']['details']
    title = ifp['props']['title']
    bins = [x['props']['title'] for x in ifp['bins']]
    rejected = []
    if 'When' in title or "By what date" in title:
        periods = get_periods_of_whenwill_question(ifp)
        rejected, filtered = filter_periods_to_today(periods)
        original_bins = bins
        event = get_event(ifp)
        bins = [f"{event} between {b} and {c}" for a,b,c in filtered]
    sb1 = '\n'.join([f"""* O{i+1}. {bin}""" for i, bin in enumerate(bins)])
    psum = '+'.join([f'P{i+1}' for i, bin in enumerate(bins)])
    pcom = ','.join([f'P{i+1}' for i, bin in enumerate(bins)])
    sbins = f"""The question has one of {len(bins)} outcomes namely  

{sb1}

Each outcome Oi has a probability Pi where 0 <= Pi <= 1.
We must have that {psum} = 1.0.
Add some reasonable amount of randomness/noise to the estimation of the branches.
The output is a Python list wrapped by a binProbs tag, in this format:
```binProbs
[{pcom}]
```
"""
    prompt = f"""
You are a talented, experienced and confident superforecaster. You are asked a question:

```question
{title}
```

You are given details on how to interpret the terms of the question:

```details
{details}
```

Your assistant has research related news and Wikipedia articles and prepared summaries of each one.
Use the data in these research summaries to analyse the question:

{research}

For you to be marked Successful, you must output 3 things:

1. Probabilities for the outcomes of the question.  
{sbins}

2. Reasons your probabilities might be right, wrapped in tag in this format:
```rRight
...reasons you might be right
```
There should be a reason you are right for each outcome ending with a forecast of form ZZ% where ZZ ranges from 0 to 100.

3. Reasons your probabilities might be wrong, wrapped in tag in this format:
```rWrong
...reasons you might be wrong
```
"""
    with open(fn, 'w') as f:
        json.dump((prompt, rejected), f)
    fn1 = fn.replace('.json', '.txt')
    with open(fn1, 'w') as f:
        f.write(prompt)

    return prompt, rejected

In [120]:
    prompt, rejected = glimt_forecast_prompt(ifp, research)

In [ ]:
print(prompt)

'General Election for New York City Mayor'

In [135]:
prompt_polls = "Any news articles giving details of election polls for {market['name']}"

In [136]:
from call_asknews import call_asknews

In [157]:
polls = call_asknews(market['name'] + " Opinion Poll Results")

In [158]:
print(polls)

Here are the relevant news articles:

**The Upper House Election and the New York Mayoral Election: A Shift in the Political Landscape?**
The recent upper house election and New York mayoral election have raised questions about the existing political landscape. In the upper house election, the ruling Liberal Democratic Party and Komeito suffered a crushing defeat, while the Constitutional Democratic Party of Japan and the Reiwa Shinsengumi Party gained significant seats. Both parties focused on the issue of 'foreigners' in their campaigns, with the Reiwa Shinsengumi Party's 'Japanese First' slogan being particularly prominent. However, the reality is that the issue of 'foreigners' is not as significant as it seems, with only 3% of welfare recipients being foreigners. The Minister of Health, Labour and Welfare, Fukuda Kazuo, stated that there is no evidence of foreigners dominating medical expenses or receiving preferential treatment in welfare. In reality, the Constitutional Democratic Party of Japan removed the phrase 're-examine excessive preferential treatment for foreigners' from their campaign promises, and the Reiwa Shinsengumi Party's leader, Kamisugi Munehisa, downplayed the issue in a press conference, saying 'Is it not true that foreigners are not privileged?' The election results showed that the Constitutional Democratic Party of Japan and the Reiwa Shinsengumi Party received a significant number of votes from young people, with 40% of their votes coming from people under 30 and 80% coming from people under 50. However, this phenomenon is not unique to Japan, with right-wing parties in other countries also gaining support from young people. For example, the Reform UK party in the UK has a high level of support among older generations, and the Republican Party in the US has a strong base of support among older generations. The recent New York mayoral election also saw a young candidate, Zohran Kwame Mamdani, win the Democratic primary with a surprise upset victory. Mamdani, who is 33 years old and has a diverse background, focused on issues such as free public transportation and rent control, and used social media platforms to reach out to young people. The results of the election showed that Mamdani received a significant number of votes from young people, with 47,000 votes, which is 6 times more than the previous winner. The election also saw a large increase in voter registration among young people, with 18-39 year olds making up a significant portion of the voters.
Original language: ja
Publish date: July 29, 2025 08:31 AM
Source:[朝日新聞デジタル](https://www.asahi.com/articles/AST7T2DRST7TULLI003M.html?iref=ogimage_rek)

**Commentary: New York City's ranked choice voting -- Democracy that's accountable to voters**
New York City's recent election, which used ranked choice voting (RCV), has shown that better elections can empower voters to choose candidates who are accountable to them. Zohran Mamdani, a 33-year-old state legislator, knocked off Andrew Cuomo, a former governor, in the mayoral primary. Mamdani's campaign was issue-driven and positive, and he engaged with voters to win their support. RCV allowed voters to rank their favorite candidates, rather than just picking one, which led to a more constructive campaign. The election showed that RCV can give voters more choice and more voice at the ballot box, and that it can lead to higher turnout and more engagement from politicians. According to an exit poll, 96% of voters found it easy to complete their ballot, and over 75% want to keep RCV or expand it to additional races. Meredith Sumpter, president and CEO of FairVote, a nonpartisan organization, notes that RCV has no party bias and is a powerful tool for building coalitions behind a future that a majority of voters support.
Original language: en
Publish date: July 29, 2025 08:28 AM
Source:[ArcaMax](https://www.arcamax.com/politics/opeds/s-3793070)

**Vote ABBEY LAUREL-SMITH for MAYOR NYC at the Ballot on Tuesday 4th of November, 2025**
Abbey Laurel-Smith, an independent mayoral candidate for New York City, emphasized the importance of 'voting for a better life' rather than 'quality of life and equity'. He stated that for the past two decades, the push for 'better life' has been overshadowed by the need for 'improvement and equity', leading to a non-sustainable cost of living, decreased safety, and a system that is administered on a 'paycheck-to-paycheck' basis. Laurel-Smith plans to pause development in Manhattan and spread it to other boroughs, addressing equity through healthcare-like solutions. He attributed the shift away from 'voting for a better life' to career politicians and the city's changing demographics, population growth, and priority on transactional arts and coding. He also highlighted the city's rise as the child poverty capital of the United States, with many kids forced to work or hustle to support their families due to high costs of living. Laurel-Smith promises to work for the general well-being of all New Yorkers, improve living experiences for retirees, students, and low-income families, and bring back high-earning out-migrators who left the city during the pandemic.
Original language: en
Publish date: July 28, 2025 10:30 PM
Source:[Newswire.com](https://www.newswire.com/news/vote-abbey-laurel-smith-for-mayor-nyc-at-the-ballot-on-tuesday-4th-of-2900275)

**Exclusive | Andrew Cuomo slams Eric Adams as ‘spoiler’ in NYC mayoral race: ‘It’s about you and your ego’**
Andrew Cuomo, a former New York governor, has accused current Mayor Eric Adams of being a 'spoiler' in the NYC mayoral race. Cuomo, who is running as an independent candidate, claims that Adams' independent re-election campaign will make it easier for socialist Zohran Mamdani to become mayor. Cuomo stated, 'If you're going to run, even if you're just a spoiler, then it's about you and your ego.' He also criticized Adams for consistently putting himself above the interests of New Yorkers. Cuomo's campaign spokesperson responded to Adams' campaign, saying, 'If Andrew Cuomo is looking for a spoiler, he should look in the mirror.' Polling shows that Mamdani could easily win the election if he faces a ballot with three independents, including Adams and Cuomo. Cuomo also accused Mamdani of offering 'hollow promises' and criticized his policy proposals, stating, 'None of it would make a difference.'
Original language: en
Publish date: July 28, 2025 06:14 PM
Source:[nypost.com](https://nypost.com/2025/07/28/us-news/andrew-cuomo-slams-eric-adams-as-spoiler-in-nyc-mayoral-race-its-about-you-and-your-ego/)

**Adams and Cuomo Engage in Mutual Criticism Ahead of November Election**
New York City Mayor Adams criticized his opponent, former Governor Cuomo, for his scandals involving sexual harassment and nursing home policies. Cuomo responded by mocking Adams for not participating in the Democratic primary, saying he knew no one would vote for him. Adams said, 'He comes from a good family. His father was a great governor, and he was re-elected three times, doing a great job. But during his time as governor, he resigned. Personal problems should not be an excuse for resignation. In my personal problems, I stood up and continued to serve this city.' Adams pointed out that he did not resign as mayor when he was federally charged, unlike Cuomo, who resigned due to allegations of sexual harassment and was criticized for his nursing home policies that led to the deaths of 15,000 elderly people in 2020. Adams said, 'This is his history, and he used the same tactics during my term as mayor. He participated in the primary and lost by a two-digit margin. He knew I would participate in the general election. Why did he join the election as an independent candidate?' Cuomo quickly responded to Adams, saying, 'He dropped out of the primary because Democratic voters wouldn't vote for him.' Cuomo remained confident, saying, 'The people who voted for me in the primary will also vote for me in November.'
Original language: zh
Publish date: July 28, 2025 02:31 AM
Source:[The Epoch Times](https://www.epochtimes.com/gb/25/7/28/n14561806.htm)

**Adams and Cuomo Trade Barbs Ahead of November Election**
New York City Mayor Adams criticized his opponent, former Governor Cuomo, for his scandals involving sexual harassment and nursing home policies. Cuomo responded by saying Adams withdrew from the Democratic primary because he knew he wouldn't get any votes. Adams said, 'He comes from a good family. His father was a great governor, and he was re-elected three times, doing a great job. But during his time in office, he resigned, citing personal problems. Personal problems shouldn't be an excuse to leave your job. In my personal problems, I stood up and continued to serve this city.' Adams pointed out that he didn't resign as mayor when he was federally charged, but instead continued to fulfill his duties. Cuomo was forced to resign due to allegations of sexual harassment and was criticized for his nursing home policies, which led to the deaths of 15,000 elderly people in 2020. Adams said, 'This is his history, and he used the same tactics during my mayoral term, 'he participated in the primary and lost by a two-digit margin. He knows I'll be in the general election. Why is he running as an independent candidate?' Cuomo quickly responded, 'He withdrew from the primary because Democratic voters wouldn't vote for him,' Cuomo said with a smile, 'I stayed in the primary, and 4 million Democratic voters voted for me.' Cuomo remains confident that 'the people who voted for me in the primary will also vote for me in November.'
Original language: zh
Publish date: July 28, 2025 02:31 AM
Source:[The Epoch Times](https://www.epochtimes.com/b5/25/7/28/n14561806.htm)

**Joseph Hernandez Launches Bid for Mayor - Queens Ledger**
Joseph Hernandez, a scientist and investor, has launched his bid for New York City mayor as an independent on a centrist platform. His campaign has gained traction, collecting over 15,000 petitions and endorsements from industry associations. Hernandez, who was born in Cuba and immigrated to the US with his family, emphasizes the importance of hard work, education, and faith in achieving the American Dream. He plans to hire 10,000 more police officers and reform the department's overtime pay to address public safety concerns. Hernandez also aims to lower housing costs by increasing the conversion of empty offices into apartments and reducing the length of time that affordable units sit unoccupied. He is a strong advocate for the use of artificial intelligence in government, citing its potential to improve city services and create jobs. Hernandez's campaign has sued the city over the lack of ranked choice voting in the general election, which he believes is unfair and violates state and federal law.
Original language: en
Publish date: July 24, 2025 08:23 PM
Source:[queensledger.com](https://queensledger.com/2025/07/24/joseph-hernandez-launches-bid-for-mayor/)

**Zohran Mamdani Leads November General Election Poll For New York City Mayor - UrduPoint**
A new independent poll shows Zohran Mamdani, the Democratic Party nominee, leading the general election for New York City mayor with 35% of voters, followed by former governor Andrew Cuomo at 25%, Republican nominee Curtis Sliwa at 14%, incumbent Mayor Eric Adams at 11%, and independent candidate Jim Walden at 1%. Thirteen percent of voters remain undecided. The poll, conducted by Slingshot Strategies, has a margin of error of 4.2 points. Mamdani's campaign is working to consolidate Democratic Party support in a city where registered Democrats outnumber Republicans 6-to-1 and unaffiliated voters 3-to-1. According to the poll, Adams trails Mamdani among every single subset of voters except Republicans, where Adams picks up 26 percent to Mamdani's 7 percent. Adams' net approval rating is at -34, while Mamdani is at +4 and Cuomo is at -2. 'Let's not forget: just weeks ago, Andrew Cuomo was ahead in multiple polls and then went on to lose the Primary by double digits,' Adams' campaign spokesperson Todd Shapiro said in a statement. 'Real New Yorkers' are 'only now tuning in,' he added, 'and voters will choose progress over extremism every time.'
Original language: en
Publish date: July 14, 2025 07:20 PM
Source:[UrduPoint](https://www.urdupoint.com/en/world/zohran-mamdani-leads-november-general-electio-2013693.html)

**Next round of NYC ranked choice voting results set to be released in mayoral election**
The next round of ranked choice voting results in New York City's primary elections is set to be released on Tuesday. Assemblyman Zohran Mamdani has claimed victory in the Democratic primary for mayor, but former Gov. Andrew Cuomo is waiting for the ranked choice voting results before deciding whether to continue his campaign as an independent. According to the first unofficial results, Mamdani is ahead with 43.5% of the vote over Cuomo's 36.4%. If Mamdani clears the 50% threshold, he will move on to the November general election, where he will face off with incumbent Mayor Eric Adams and Republican nominee Curtis Sliwa. Cuomo plans to stay on the ballot for the general election but is still deciding whether to actually campaign, saying, 'We're going to be looking at the numbers that come in from the primary, and then we have to look at the landscape in the general election, which is a totally different landscape.'
Original language: en
Publish date: July 01, 2025 11:25 AM
Source:[CBS News](https://www.cbsnews.com/newyork/news/nyc-mayor-election-ranked-choice-voting-results/)

**New York’s Unsettling Mayoral Race**
The recent New York mayoral election saw a surprising victory for Zohran Mamdani, a progressive candidate who ran on a platform of free buses, universal childcare, and rent control. Mamdani's message resonated with voters who were dissatisfied with the incumbent mayor, Eric Adams, and his handling of public safety and quality of life issues. Adams, who dropped out of the Democratic primary and ran as an independent, was criticized for his cronyism and erratic behavior. The other Democratic candidates, including Andrew Cuomo, were unable to generate interest with their consultant-tested, progressive-lite platforms. Cuomo, who entered the race late, was seen as a centrist but was compromised by his own political past, including his record on crime and his warning against taxing the wealthy. Mamdani's victory was seen as a rejection of the status quo and a desire for a more dramatic change in city politics. 'Our city is in crisis,' Cuomo warned, mostly one of crime and quality of life. 'Nothing works without public safety,' he said two weeks before the primary. 'People feel the city’s out of control.' His solutions were just as direct. Reporters snarked that Cuomo cribbed his policies from ChatGPT, but simplicity was the point. He’d put more cops on the streets and subways, for example, raising the level to nearly 39,000, close to early 1990s highs. (He was unclear about how he would pay for this: savings would apparently come from reduced overtime.) He’d expand involuntary treatment for the seriously mentally ill. And he wouldn’t raise taxes. Cuomo derided Mamdani’s agenda as “Everything free... tax the rich.” He warned against “class warfare,” arguing that wealthy residents would flee. “We lost 500,000 people since Covid.... People will say, I’m going to Florida, I’m going to Texas … especially since the quality of life has deteriorated.
Original language: en
Publish date: July 01, 2025 12:00 AM
Source:[city-journal.org](https://www.city-journal.org/article/new-york-city-mayoral-race-candidates-voters)

**Brooklyn Electorate Keeps an Eye on the November General Election Prize**
Mamdani, a 33-year-old Democratic Socialist, has been unofficially declared the Democratic mayoral nominee in New York City. He won 43% of the vote with 432,305 votes, compared to Cuomo's 36.4% and 361,840 votes. Cuomo conceded, saying 'Tonight was Assemblyman Mamdani's night, and he put together a great campaign.' Mamdani's campaign focused on progressive issues such as free buses, child care, healthcare, and rent freezing and affordable housing. He also received support from white progressives, and Asian and Latino voters. The general election will take place on November 4th, 2025, and Cuomo has not ruled out running as an Independent candidate. Republican Curtis Sliwa will also be on the ballot. Brooklynites led the city in voter turnout, with over 261,000 people casting their ballots in the nine days of early voting. Other notable winners include Public Advocate Jumanne Williams, who sailed through his primary with over 630,000 votes, and Brooklyn Borough President Antonio Reynoso, who faced off against challenger Khari Edwards. 'I will be the mayor for every New Yorker,' Mamdani proclaimed on election night.
Original language: en
Publish date: June 27, 2025 12:00 AM
Source:[ourtimepress.com](https://ourtimepress.com/brooklyn-electorate-keeps-an-eye-on-the-november-general-election-prize/)

**Track NYC mayor election results live as they come in**
New York City Democrats are voting in the mayoral primary, with a choice between Andrew Cuomo, Zohran Mamdani, and other lesser-known candidates. The ranked-choice system means that a winner may not be announced on Tuesday night. Polls opened at 6 a.m. and close at 9 p.m. Results can be tracked online. The outcome could indicate what kind of leader Democrats are looking for during President Donald Trump's second term, as stated by NBC New York.
Original language: en
Publish date: June 24, 2025 09:40 AM
Source:[NBC New York](https://www.nbcnewyork.com/news/politics/track-nyc-mayor-election-results-live/6313684/)

**Opinion | New York mayor primary spurs unwarranted freakout about instant runoffs**
The Democratic primary for New York City mayor is sparking concerns about the use of instant runoff voting, also known as ranked-choice voting. Critics fear that the system could allow a democratic socialist to win the election by consolidating support from a fragmented left. However, proponents argue that the system encourages candidates to broaden their appeal and achieve consensus, rather than going negative. A recent poll showed that former governor Andrew M. Cuomo, who is deeply flawed, is leading democratic socialist Zohran Mamdani, but the system could still allow Mamdani to win if his supporters rank Cuomo as their second choice. Ranked-choice voting has been used successfully in other places, such as Alaska and D.C., and has had a moderating influence on the results. However, New York's approach to the system is criticized for being slow and for only using it in primaries, not general elections.
Original language: en
Publish date: June 22, 2025 10:00 AM
Source:[Washington Post](https://www.washingtonpost.com/opinions/2025/06/22/ranked-choice-voting-nyc-virginia/)

**New York City Mayoral Debate: Cuomo and Mamdani Lead the Polls**
The second debate for the New York City mayoral election is taking place on June 12, with Andrew Cuomo and Zohran Mamdani leading the polls. According to a Marist Institute of Public Opinion (MIPO) study in early May, Cuomo had over 60% of the votes, followed by Mamdani with around 40%. However, a new poll presented by Justin Brannan's campaign for City Comptroller in early June showed Mamdani surpassing Cuomo by four points. Mamdani's campaign has been 'disciplined and grassroots, relentlessly focused on an agenda to address the crises in the lives of workers,' according to Andrew Epstein, Mamdani's spokesperson. Alexandria Ocasio-Cortez has also endorsed Mamdani, stating that he has 'demonstrated a true capacity on the ground to form a coalition of working-class New Yorkers with the greatest force to lead the group.' The election is scheduled for June 24, with early voting starting on June 14 and ending on June 22.
Original language: es

In [140]:
prompt2 = f"""{prompt}

Also take into account these articles discussing election polls for {market['name']}:

{polls}"""

In [143]:
with open('foo.txt', 'w') as f:
    f.write(prompt2)

In [148]:
!emacs foobar.txt

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [150]:
with open('foobar.txt', 'r') as f:
    prompt2 = f.read()

In [151]:
    ## Run the prompt 5 times
    prompt_tries = 1 # Waste of time on Mistral 4 bit
    answers = [humor_me(prompt2, i+1) for i in range(prompt_tries)]

START model mistral-small3.2:24b-instruct-2506-q4_K_M
model mistral-small3.2:24b-instruct-2506-q4_K_M minutes 0.10967367092768351

```binProbs
[0.25, 0.20, 0.40, 0.15]
```

```rRight
O1. Curtis Sliwa has a strong Republican base and is competitive in recent polling, which suggests he could win the election. His support is around 10-22%, and with the right campaign developments, he could consolidate more votes. Forecast: 25%.

O2. Andrew Cuomo is running as an independent and has a viable third-party challenge, with support around 23-29%. His experience and name recognition could help him win, especially if he can attract more undecided voters. Forecast: 20%.

O3. Zohran Mamdani is the Democratic nominee and leads in most recent polls with support around 26-41%. His progressive platform and consolidation of Democratic support make him the frontrunner. Forecast: 40%.

O4. Eric Adams, the incumbent, is trailing with poor approval ratings and support around 13-16%. His chances appear slim based on current data, but he could still attract some undecided voters. Forecast: 15%.
```

```rWrong
O1. Curtis Sliwa's support is still below the frontrunner, and the high level of undecided voters could shift the race. Additionally, his campaign might not have the resources to compete effectively against better-funded candidates. Forecast: 25%.

O2. Andrew Cuomo's independent status could limit his appeal to a broader electorate, and his support might not be enough to overcome the Democratic nominee's lead. Forecast: 20%.

O3. Zohran Mamdani's lead is narrow, and the race is highly competitive. A significant portion of voters is undecided, and campaign developments could change the dynamics. Forecast: 40%.

O4. Eric Adams' poor approval ratings and trailing position make it unlikely for him to win, but political upsets can happen, and he could still attract some last-minute support. Forecast: 15%.
```

In [152]:
df_yes

,name,longDescription,lastTradeDate,underlyingName,conid,underlyingConid,underlyingSymbol,shortDescription,strikeLabel,OI,probability_pct,weekly_volume,yesNo,category
0,MNYCG Nov04'25 Sliwa,Will Curtis Sliwa win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056496,796056051,MNYCG,MNYCG Nov04'25 Sliwa YES @FORECASTX,Sliwa,68300.0,5.0,4130.0,YES,Election
2,MNYCG Nov04'25 Cuomo,Will Andrew Cuomo win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056506,796056051,MNYCG,MNYCG Nov04'25 Cuomo YES @FORECASTX,Cuomo,27800.0,16.0,2775.0,YES,Election
4,MNYCG Nov04'25 Mamdani,Will Zohran Mamdani win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056520,796056051,MNYCG,MNYCG Nov04'25 Mamdani YES @FORECASTX,Mamdani,1200000.0,68.0,40527.0,YES,Election
6,MNYCG Nov04'25 Adams,Will Eric Adams win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056531,796056051,MNYCG,MNYCG Nov04'25 Adams YES @FORECASTX,Adams,202000.0,8.0,10940.0,YES,Election

In [ ]:
    binProbs = [get_bin_probs(a) for a in answers]
    rights = [get_rights(a) for a in answers]
    wrongs = [get_wrongs(a) for a in answers]
    ## Median forecasts and rationales
    forecast = rejected + median_forecast(binProbs)
    right = median_rationale(rights)
    wrong = median_rationale(wrongs)
    result = (forecast, right, wrong, sources)
    fn = f'glimt/forecast'
    import os
    os.makedirs(fn, exist_ok=True)
    fn = f"{fn}/{ifp['id']}.json"
    import json
    with open(fn, 'w') as f:
        json.dump(result, f)

In [70]:
df

,name,longDescription,lastTradeDate,underlyingName,conid,underlyingConid,underlyingSymbol,shortDescription,strikeLabel,OI,probability_pct,weekly_volume,yesNo,category
0,MNYCG Nov04'25 Sliwa,Will Curtis Sliwa win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056496,796056051,MNYCG,MNYCG Nov04'25 Sliwa YES @FORECASTX,Sliwa,68300.0,5.0,4130.0,YES,Election
1,MNYCG Nov04'25 Sliwa,Will Curtis Sliwa win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056501,796056051,MNYCG,MNYCG Nov04'25 Sliwa NO @FORECASTX,Sliwa,68300.0,96.0,4130.0,NO,Election
2,MNYCG Nov04'25 Cuomo,Will Andrew Cuomo win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056506,796056051,MNYCG,MNYCG Nov04'25 Cuomo YES @FORECASTX,Cuomo,27800.0,16.0,2775.0,YES,Election
3,MNYCG Nov04'25 Cuomo,Will Andrew Cuomo win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056511,796056051,MNYCG,MNYCG Nov04'25 Cuomo NO @FORECASTX,Cuomo,27800.0,85.0,2775.0,NO,Election
4,MNYCG Nov04'25 Mamdani,Will Zohran Mamdani win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056520,796056051,MNYCG,MNYCG Nov04'25 Mamdani YES @FORECASTX,Mamdani,1200000.0,68.0,40527.0,YES,Election
5,MNYCG Nov04'25 Mamdani,Will Zohran Mamdani win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056525,796056051,MNYCG,MNYCG Nov04'25 Mamdani NO @FORECASTX,Mamdani,1200000.0,33.0,40527.0,NO,Election
6,MNYCG Nov04'25 Adams,Will Eric Adams win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056531,796056051,MNYCG,MNYCG Nov04'25 Adams YES @FORECASTX,Adams,202000.0,8.0,10940.0,YES,Election
7,MNYCG Nov04'25 Adams,Will Eric Adams win the New York City general election for mayor in 2025?,20251129,General Election for New York City Mayor,796056534,796056051,MNYCG,MNYCG Nov04'25 Adams NO @FORECASTX,Adams,202000.0,93.0,10940.0,NO,Election

In [72]:
[x['props']['title'] for x in ifp['bins']]

['The following resolves as YES: Will Curtis Sliwa win the New York City general election for mayor in 2025?. Last trade date 20251129. Contract ID: 796056496',
 'The following resolves as NO: Will Curtis Sliwa win the New York City general election for mayor in 2025?. Last trade date 20251129. Contract ID: 796056501',
 'The following resolves as YES: Will Andrew Cuomo win the New York City general election for mayor in 2025?. Last trade date 20251129. Contract ID: 796056506',
 'The following resolves as NO: Will Andrew Cuomo win the New York City general election for mayor in 2025?. Last trade date 20251129. Contract ID: 796056511',
 'The following resolves as YES: Will Zohran Mamdani win the New York City general election for mayor in 2025?. Last trade date 20251129. Contract ID: 796056520',
 'The following resolves as NO: Will Zohran Mamdani win the New York City general election for mayor in 2025?. Last trade date 20251129. Contract ID: 796056525',
 'The following resolves as YES: Will Eric Adams win the New York City general election for mayor in 2025?. Last trade date 20251129. Contract ID: 796056531',
 'The following resolves as NO: Will Eric Adams win the New York City general election for mayor in 2025?. Last trade date 20251129. Contract ID: 796056534']

In [74]:
forecast[0][::2]

[0.1, 0.05, 0.05, 0.2]

In [66]:
contracts = df.to_dict(orient='records')

In [67]:
contracts = {contract['conid']: contract for contract in contracts}

In [68]:
for ifp in ifps:
    fn = f'glimt/forecast'
    fn = f"{fn}/{ifp['id']}.json"
    with open(fn, 'r') as f:
        forecast = json.load(f)
    [[Pyes, Pno], Rfor, Ragainst, sources] = forecast
    contract = contracts[ifp['id']]
    yesNo = contract['yesNo']
    pct = contract['probability_pct']
    yesPct = pct if yesNo == 'YES' else 100-pct
    noPct = 100-pct if yesNo == 'YES' else pct
    report = f"""
{ifp['props']['title']}
{ifp['props']['shortTitle']}

YES {100*Pyes} bot / {yesPct} crowd
NO  {100*Pno} bot  / {noPct} crowd

Reasons for YES
===============
{Rfor}

Reasosn for NO
==============
{Ragainst}

----------------------------------------"""
    print(report)

ValueError: too many values to unpack (expected 2)